name: SPDX Dependency Graph Snapshot Submission
on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: '31 5 * * 2'

jobs:
  find-sboms:
    runs-on: ubuntu-latest
    outputs:
      sboms: ${{ steps.generate_js_array.outputs.sboms }}
    steps:
      - uses: actions/checkout@v4

      - name: Find SBOM files and set output
        id: generate_js_array
        run: |
          sboms=$(find . \( -path '*/spdx2.2/*' -o -path '*/spdx2.3/*' \) -name '*.spdx.json' | xargs -n 1 dirname | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "sboms=$sboms" >> $GITHUB_OUTPUT

  process-sboms:
    needs: find-sboms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sbom: ${{ fromJson(needs.find-sboms.outputs.sboms) }}

    steps:
      - name: Print GitHub Context
        run: |
          echo '${{ toJson(matrix) }}' | jq -r 'paths | map(tostring) | join(".")' | while read path; do
            echo "$path: $(echo '${{ toJson(matrix) }}' | jq -r .$path)";
          done

      - name: Checkout repository
        uses: actions/checkout@v4

      # Format corrleator as "job(matrixvalue1, matrixvalue2, ... )" or just "job" with a null matrix
      - name: Define correlator
        id: matrix_parser
        run: |
            correlator=$(echo '${{ toJSON(matrix) }}' | jq -r 'if . == null then "${{ github.job }}" else "${{ github.job }}(" + ([.[] | tostring] | join(", ")) + ")" end')
            echo "correlator=$correlator" >> $GITHUB_OUTPUT

      - name: SBOM upload
        uses: advanced-security/spdx-dependency-submission-action@input-correlator
        with:
          filePath: "${{ matrix.sbom }}"
          correlator: ${{ steps.matrix_parser.outputs.correlator }}

      # - name: Validate SPDX 3.0 Documents
      #   run: |
      #     SPDX30_SCHEMA_URL="https://spdx.org/schema/3.0.0/spdx-json-schema.json"
      #     SPDX30_SHACL_URL="https://spdx.org/rdf/3.0.0/spdx-model.ttl"

      #     for f in $(find . -type f -path '*/spdx-3.0/*.json'); do
      #         echo "Checking $f..."
      #         check-jsonschema -v --schemafile $SPDX30_SCHEMA_URL $f
      #         pyshacl -s $SPDX30_SHACL_URL -e $SPDX30_SHACL_URL $f
      #     done
